### ISSUE TITLE
FlashPage error while uploading the new code to arduino due.

### ISSUE THREAD

**Issue by pdborhad** [sebnil/DueFlashStorage#10]
Hi,

I am not sure if I am raising an issue here would help me. However, the issue is bit serious and related to flash memory in Arduino Due. If you think this is not related to the DueFlashStorage libray, I will remove this from this page. 

I am facing a serious problem with Arduino due. In my application, I am using this library to save some data to flash memory as Arduino due has no EEPROM. I am using this library to save the data. Once I program the board, it works good. But when I change something in my code and try to upload I am facing "Flash page locked" error message and it could not load the program to the board. There is no particular pattern that I can explain here when this issue occur. Sometimes, I upload the program 5 - 6 time, then this issue comes, or sometime in the second attempt it happened. Once this issue occur, the program can not be loaded to the board. I tried by pressing the erase button and then reset, but it did not help. The standard Bilnk Led program also does not work. It gives same error flash page locked. After this I have to do nothing but change the board. Till now, I have broken six board. 
Please let me know if you can help me here. 

I am using following memory locations in flash to save the data. 

const short saveIntoEEPROMAddress = 196;
const short firstIrrStrtAddress = 200;
const short motorStatusAddress = 92; 		// save the motor states. 0=; 1=left, 2=right, 3=cutback
const short currIrrStartAdd = 100;
const short controllerSuspendAddr = 96; 	// Location on EEPROM for surgeSuspended variable
const short totalDataAddress = 300;
const short totalDataPerEventAddress = 305;
const short numOfEventsCompAddress = 310;	
const short lastEventTimeAddress = 315;
const short totalTimeAddress = 320;

I am facing following error while uploading blink program. 

Please take a look on following link to know more about issue. 
https://github.com/arduino/ArduinoCore-sam/issues/45

Regards,
Prash

**Comment by sebnil** [comment]
Not related to this library. Hope you find a solution. Closing issue.
