### ISSUE TITLE
Adding the DueFlashStorage library affects the results of my code

### ISSUE THREAD

**Issue by gmeijer** [sebnil/DueFlashStorage#11]
I have some code to read monitor the energy usage in my home, similar to that of Emonlib.

Without the DueFlashStorage the code works as expected. However, as soon as I add the following lines to my code, the measurement results of my code change:
#include <DueFlashStorage.h>
DueFlashStorage dueFlashStorage;

How is it possible that only addding these 2 lines of code can affect the output results? Where can I start looking?
Kind regards,
                     Gerard.

**Comment by sebnil** [comment]
A tip is to go back to a very minimal kind of example. Then add piece by piece until it breaks, and then you will know where to look. 

Regards,
Sebastian
