### ISSUE TITLE
DueFlashStorageExample does not compile

### ISSUE THREAD

**Issue by codecees** [sebnil/DueFlashStorage#16]
Unless I specifically add a block size of 1 in all read/write calls.
This is on Arduino 1.8.10.

**Comment by sebnil** [comment]
Does the example code compile and work as intended?

**Comment by sebnil** [comment]
No response. Closing issue.

**Comment by codecees** [comment]
The examples did not compile

**Comment by sebnil** [comment]
Just tried it. Works fine. You need to give me a bit more details. 
![image](https://user-images.githubusercontent.com/1711012/78467267-1d3e5480-774e-11ea-812b-cccde84861fb.png)

**Comment by kyuhyong** [comment]
the example code does not compiled even for Arduino due board nor for my mega2560 board.
![image](https://user-images.githubusercontent.com/22294429/100820053-c3cf2680-3490-11eb-8441-7b32213a6a19.png)

I see errors below
Arduino\libraries\DueFlashStorage\src/efc.h:116:19: error: 'Efc' was not declared in this scope
Arduino\libraries\DueFlashStorage\src/efc.h:116:24: error: 'p_efc' was not declared in this scope
Arduino\libraries\DueFlashStorage\src/efc.h:116:40: error: expected primary-expression before 'ul_access_mode'
Arduino\libraries\DueFlashStorage\src/efc.h:116:65: error: expected primary-expression before 'ul_fws'
Arduino\libraries\DueFlashStorage\src/efc.h:117:32: error: variable or field 'efc_enable_frdy_interrupt' declared void
