### ISSUE TITLE
Can't read or  write float values on the adress specified

### ISSUE THREAD

**Issue by ghost** [sebnil/DueFlashStorage#17]
Hello, I'm using an arduino due with due board version 1.6.12 and an IDE arduino 1.8.12. 

My code is the following:

`
#include <DueFlashStorage.h>
DueFlashStorage dueFlashStorage;

void setup() {
  Serial.begin(9600);
  
}

void loop() {

  float aModif = dueFlashStorage.read(0);
  Serial.print("aModif =");Serial.println(aModif); 
  aModif=aModif + 0.1 ;
  dueFlashStorage.write(0,aModif);
  delay(1000);
 
}

`
I have the following results on serial:
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00
aModif =255.00

My question is, how can I read or write an increment of 0.1 in the specified adress ?

Thanks in advance.

**Comment by sebnil** [comment]
Hi!
The command is:
	boolean write(uint32_t address, byte value);
	
You are writing a float. That is probably the issue.

You can write a float but then you need to convert it to a pointer or a struct:
boolean write(uint32_t address, byte *data, uint32_t dataLength);
