### ISSUE TITLE
flash write error

### ISSUE THREAD

**Issue by iddq** [sebnil/DueFlashStorage#18]
I use a slightly modified version of your lib for years and I faced a strange problem. If there is a longer period between writes (10+ days) then the writes will be unsuccessful until system reset. Have you experienced similar problem ever?

**Comment by Yash1903** [comment]
can i make files(like...text or json) using this library  and also write,append and read.........
if yes. 
can you Share example of it. (Store in DUE)

**Comment by sebnil** [comment]
> I use a slightly modified version of your lib for years and I faced a strange problem. If there is a longer period between writes (10+ days) then the writes will be unsuccessful until system reset. Have you experienced similar problem ever?

No I have not seen that. Sorry.

**Comment by sebnil** [comment]
> can i make files(like...text or json) using this library and also write,append and read.........
> if yes.
> can you Share example of it. (Store in DUE)

No, sorry.
