### ISSUE TITLE
Where to safely store one byte of data?

### ISSUE THREAD

**Issue by fredlcore** [sebnil/DueFlashStorage#19]
Hi, first of all thanks a lot for this great library!
I have read #7, and thanks to the instructions there, I found out that my sketch which consumes approx. 65% of flash memory, goes way beyond 0xC0000 which you said is the place where data gets stored by default in your library.
I have three questions:
1. Why did you use 0xC0000 and not something like 0xFF000 which should almost never be occupied?
2. How can I tell the write function to start writing from a different offset?
3. (and probably most important for me) Is there a way I can 'reserve' flash memory by for example putting an unused string in flash and use that to store my data?

All I need is just one byte, but that one byte could still destroy my code, so I have to make sure it works even if the code is continuing to grow (which it will).

Thanks a lot again for your great work!

**Comment by sebnil** [comment]
Thanks, and glad you like the library. Sorry, I will not have time to look into this. I suggest you just try it out and see what works. There was probably a reason why 0xc0000 was used but I can't remember. Probably a compromise between code space and storage space.
