### ISSUE TITLE
Please tag the current commit as v1.0

### ISSUE THREAD

**Issue by rmcolbert** [sebnil/DueFlashStorage#6]
The Adruino library manager needs the master branch to be tagged so it can add it to the list.  I have submitted the request to have it monitor the repository.

**Comment by sebnil** [comment]
git rookie here. i made a commit with a 1.0 tag. please check if it is ok. if not then open a new ticket and i will make another try.

and thank you for helping me putting this on the arduino repo!

**Comment by rmcolbert** [comment]
DueFlashStorage is now listed in the Arduino library manager.  There was a question about having #FLASH_DEBUG enabled by default possibly causing issues once the Serial buffer is full if not connected.  If it should be turned off by default, please commit that change & tag with v1.0.1 and the change will be automatically pushed to the library.

-Robert
