### ISSUE TITLE
Where ends my virtual EEPROM? Where starts my sketch?

### ISSUE THREAD

**Issue by varlux** [sebnil/DueFlashStorage#7]
Hi everybody,

```
 now in my project I want to store lots of configuration data, and my sketch iv very big.
```

So...I am very scared....because I don't know if my configuration overwrite the code or if the code overwrite configuration data.

Are there struments to check it?!?

Thanks

**Comment by DukeOfDelmar** [comment]
You can perform an assembly dump of your compiled sketch to see where your sketch begins and ends.  If you are using the Arduino IDE with your Due:

1. Find your ARM compiler folder.  For me on Win10x64, this was located at "C:\Users\{MyUserName}\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/".

2. Find the temp folder where the IDE places your compiled sketch.  This will be a path with a big long hex number in it, and it can be found by looking at the stream of command lines in the compiler output window.  For the sketch I am currently working on, this is located at "C:\Users\{MyUserName}\AppData\Local\Temp\build18d60ba4755531006dd9df0e89f991f0.tmp".

3. Open a command prompt in the temp folder found in step 2.  In Win10, this can be done by navigating to the folder in File Explorer, and then shift-right-clicking the window background and choosing the "Open Command Prompt Here" option.

4. Construct a command line to dump the assembly listing from the path found in step 1 and the name of your sketch, and run it in the command prompt window.
Example (all on one line):
`"C:\Users\{MyUserName}\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-objdump" -S MySketch.ino.elf > MySketch.asm`
You may want to save this command line for later use.  It should stay the same for the lifetime of your sketch.

5. Open the resulting .asm file in your favorite text editor.  From there you can see the addresses where your compiled program will be located when uploaded in the leftmost 8 columns.

80000 is the start of flash. fffff is the end of flash.  By default, the library starts writing at c0000,  At the end, you will see locations starting with 20070000, that gets placed in RAM on load.

You can learn a LOT by studying your assembly listing.  It tries its best to match up your source code to the assembly instructions generated, but it won't be 100% perfect.

**Comment by pdborhad** [comment]
Hi,

I am posting this question to understand how do we decide the address of the location 0 if we use this library. 
If the address of flash starts from 80000, if we read the location dueflashstorage.read(0), which address location does it read from? And it it points to 80000, then this location would have the first instruction of the loaded program. 

Regards,
P

**Comment by sebnil** [comment]
Question answered. Closing.
